Error logged at: 05:17:59 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:02 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:04 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:07 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:15 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:18 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:21 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:23 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:25 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:29 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:32 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:34 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:37 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:40 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:43 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:45 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:50 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:52 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:18:55 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:03 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:14 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:17 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:20 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:22 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:24 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:28 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:30 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:33 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

Error logged at: 05:19:40 31-03-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "DiscordMusicBot.py", line 139, in play
    ytUrl = getYtLink(track[0])
  File "DiscordMusicBot.py", line 80, in getYtLink
    print('Done getYtLink')
OSError: [Errno 5] Input/output error

